name: Destroy Vertica DB

on:
  workflow_dispatch: {}

concurrency:
  group: vertica-db-${{ github.ref }}
  cancel-in-progress: true

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Clear stale Terraform lock (idempotent)
        working-directory: infra
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: ./clear-stale-lock.sh

      - name: Backend & init
        working-directory: infra
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          bash backend-bootstrap.sh
          ./clear-stale-lock.sh
          terraform init

      - name: Destroy
        working-directory: infra
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          ./clear-stale-lock.sh
          terraform destroy -auto-approve || true
